out := '../rvsol/out'

bindings-upgrades:
  #!/usr/bin/env bash
  set -euxo pipefail

  build_abi() {
    jq .abi "{{out}}/$1.sol/$1.json" > "/tmp/$1.json"

    local lowercase=$(echo "$1" | awk '{print tolower($0)}')
    abigen \
      --abi "/tmp/$1.json" \
      --pkg bindings \
      --out "bindings/$lowercase.go" \
      --type $1
  }

  build_abi RISCV
  build_abi PreimageOracle
