FROM golang:1.21.1-alpine3.18 AS builder
WORKDIR /build

# Copy the context into the container
ADD . .

# Install deps
RUN apk add --no-cache git make bash

RUN --mount=type=cache,target=/go/pkg/mod --mount=type=cache,target=/root/.cache/go-build make

FROM alpine:3.18 AS export

RUN apk add --no-cache bash
COPY --from=builder /build/rvgo/bin/asterisc /usr/local/bin/asterisc
ENTRYPOINT ["asterisc"]
