[profile.default]
src = 'src'
out = 'out'
script = 'scripts'
libs = ['lib']
optimizer = true
optimizer_runs = 999999
remappings = [
  '@optimism/=lib/optimism/packages/contracts-bedrock',
  '@openzeppelin/contracts-upgradeable/=lib/optimism/packages/contracts-bedrock/lib/openzeppelin-contracts-upgradeable/contracts',
  '@openzeppelin/contracts/=lib/optimism/packages/contracts-bedrock/lib/openzeppelin-contracts/contracts',
  '@lib-keccak/=lib/optimism/packages/contracts-bedrock/lib/lib-keccak/contracts/lib',
  '@solady/=lib/optimism/packages/contracts-bedrock/lib/solady/src',
  'safe-contracts/=lib/optimism/packages/contracts-bedrock/lib/safe-contracts/contracts',

  # We need these remappings to use the Optimism monorepo contracts as a library.
  'src/dispute=lib/optimism/packages/contracts-bedrock/src/dispute',
  'src/libraries=lib/optimism/packages/contracts-bedrock/src/libraries',
  
  'forge-std/=lib/forge-std/src',
  'ds-test/=lib/forge-std/lib/ds-test/src',
]

ffi = true
fs_permissions = [
  { access='read-write', path='./deployments' },
  { access='read', path='./' }
]

[fmt]
line_length=120
multiline_func_header='all'
bracket_spacing=true
wrap_comments=true

# See more config options https://github.com/foundry-rs/foundry/tree/master/config