[profile.default]
src = 'src'
out = 'out'
script = 'scripts'
libs = ['lib']
optimizer = true
optimizer_runs = 999999
remappings = [
  '@optimism/=lib/optimism/packages/contracts-bedrock',
  '@openzeppelin/contracts-upgradeable/=lib/optimism/packages/contracts-bedrock/lib/openzeppelin-contracts-upgradeable/contracts',
  '@openzeppelin/contracts/=lib/optimism/packages/contracts-bedrock/lib/openzeppelin-contracts/contracts',
  '@lib-keccak/=lib/optimism/packages/contracts-bedrock/lib/lib-keccak/contracts/lib',
  '@solady/=lib/optimism/packages/contracts-bedrock/lib/solady/src',
  '@rari-capital/solmate=lib/optimism/packages/contracts-bedrock/lib/solmate',
  'safe-contracts/=lib/optimism/packages/contracts-bedrock/lib/safe-contracts/contracts',

  # We need these remappings to use the Optimism monorepo contracts as a library.
  'src/dispute=lib/optimism/packages/contracts-bedrock/src/dispute',
  'src/libraries=lib/optimism/packages/contracts-bedrock/src/libraries',
  'interfaces=lib/optimism/packages/contracts-bedrock/interfaces',
  'scripts/libraries=lib/optimism/packages/contracts-bedrock/scripts/libraries',
  'test/mocks=lib/optimism/packages/contracts-bedrock/test/mocks',

  # required for etherscan contract verification
  'src/L1=lib/optimism/packages/contracts-bedrock/src/L1',
  'src/legacy=lib/optimism/packages/contracts-bedrock/src/legacy',
  'src/universal=lib/optimism/packages/contracts-bedrock/src/universal',
  'src/cannon=lib/optimism/packages/contracts-bedrock/src/cannon',

  '@forge-std/=lib/forge-std/src',
  'ds-test/=lib/forge-std/lib/ds-test/src',
  'forge-std/=lib/optimism/packages/contracts-bedrock/lib/forge-std/src',
]

ffi = true
fs_permissions = [
  { access='read-write', path='./deployments' },
  { access='read', path='./' }
]

[fmt]
line_length=120
multiline_func_header='all'
bracket_spacing=true
wrap_comments=true

# See more config options https://github.com/foundry-rs/foundry/tree/master/config